### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by meonkeys** [papertrail/remote_syslog2#129]
Does remote_syslog respect OS-level proxies?

I'm running it on a Synology NAS (Intel chip, 64-bit Linux), and messages aren't getting to Papertrail. There might be some other outbound filtering problem, but I just wanted to rule out proxy issues.

The proxy works as expected for this test in the python shell:

```python
import urllib2
response = urllib2.urlopen('http://python.org/')
html = response.read()
```

**Comment by troy** [comment]
What kind of proxy? remote_syslog isn't using HTTP, so an HTTP proxy isn't relevant.

Almost no daemons support SOCKS proxies, rs2 included.

An SSH proxy (AKA SSH tunnel, like with `ssh -L`) will automatically work, since it's invisible to the daemon.

**Comment by meonkeys** [comment]
I think this is just a proxy for HTTP/S traffic. The other info you provided is helpful, thank you. I'll add more info if/when I learn more about what the heck is going on with my setup. Closing for now.
