### ISSUE TITLE
Daemonized remote_syslog2 just exits on dockerized ubuntu

### ISSUE THREAD

**Issue by marick** [papertrail/remote_syslog2#13]
We're running remote_syslog2 to pick up the log from a single app running in a Docker container (virtual Linux) on AWS. When run with the -D argument, it works. When run without, remote_syslog2 seems to immediately exit. Here's a sample run:

```
./remote_syslog --debug-log-cfg="/tmp/log.txt" --configfile="remote_syslog_conf.yaml" --hostname="awspartners"
```

It creates the debug log file, but it's empty:

```
root@71fbad9baea6:/# ls -l /tmp/log.txt
-rw-r--r-- 1 root root 0 Jul  2 02:07 /tmp/log.txt
```

And the process does not exist(*):

```
root@71fbad9baea6:/# ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /bin/bash
   26 ?        R+     0:00 ps ax
```

(_) Like I said, this Ubuntu is *very_ stripped down. This is all it contains:
- Ubuntu 14.04
- lucid (10.04) minimal
- precise (12.04) minimal
- quantal (12.10) minimal
- raring (13.04) minimal
- saucy (13.10) minimal
- trusty (14.04) minimal

https://registry.hub.docker.com/_/ubuntu/

**Comment by vmatekole** [comment]
Hi, I have a similar issue - https://registry.hub.docker.com/u/vmatekole/remote_syslog2/dockerfile/ 
Using this command - docker run -d  -v /var/log:/var/log --name logger vmatekole/remote_syslog2 --debug-log-cfg=/var/log/remote_log.log --no-detach=true  --pid-file="/tmp/remote_syslog2.pid" --tcp -d log2.papertrail.com -p xxxx /var/log/spree-vend/production.log

Again, nothing appears in the debug log.

**Comment by troy** [comment]
@vmatekole what version os rs2 are you using? Is it above the version mentioned above?

Also, you're using both the wrong hostname and wrong domain name. Change `log2.papertrail.com` to `logs2.papertrailapp.com` (or copy and paste what Papertrail's site says to use).

**Comment by vmatekole** [comment]
@troy  - I am using 0.13 - I have corrected the url... However, now I get - INFO  remote_syslog.go:114 Connecting to logs2.papertrailapp.com:XXXX over tcp
2015-04-04 15:14:21 CRITICAL  remote_syslog.go:118 Cannot connect to server: dial tcp: lookup logs2.papertrailapp.com: no such host. I can telnet from the host of the container, strange. Will investigate further.

**Comment by troy** [comment]
Sounds like you don't have DNS in the container. See [my Docker container doesn't have DNS, WTF](https://www.google.com/search?q=no+dns+in+container+docker)

**Comment by vmatekole** [comment]
@troy  Thank you! Really helpful!
