### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by jstarcher** [papertrail/remote_syslog2#130]
After a quick analysis I don't see any FreeBSD support, though I think the port would be fairly straightforward. Am I just not seeing how to compile in FreeBSD or does this support need added?

**Comment by troy** [comment]
We're not sure and don't have a way to test. If you're inclined to try compiling and/or using it, feel free: https://github.com/papertrail/remote_syslog2#development

If it builds and runs, we'd consider trying to cross-compile for fbsd as well.
