### ISSUE TITLE
Trace/breakpoint trap running on AWS Linux 2016.3

### ISSUE THREAD

**Issue by nigelfo** [papertrail/remote_syslog2#133]
Running fine on AWS Linux latest version of 2015.09.  Upgrade to 2016.03 and it fails to start:

dmesg:
traps: remote_syslog[25739] trap int3 ip:80763c7 sp: ff8e8778 error:0

Launched clean 2016.03 AMI, downloaded latest version from Github (not the beta package) exactly the same error.

**Comment by traviscollins** [comment]
Probably using the wrong RPM. Use x64 instead the i386 RPM.

**Comment by zhedar** [comment]
@traviscollins You're right, using `remote_syslog_linux_amd64.tar.gz` works as intended, while `remote_syslog_linux_i386.tar.gz` doesn't. Probably took the wrong binary by accident, as the `amd` in the file name didn't look familiar.

**Comment by mookie5dc** [comment]
do you know if the remote_syslog_linux_amd64.tar.gz will work with the older linux version? (2015.09)

**Comment by johlym** [comment]
Hi Dale,

I don’t see why not. I don’t have any reports of it not working. the rpm and tar files are the same binary (if your arch matches), just different methods of installing.
