### ISSUE TITLE
For new log files the first line is skipped

### ISSUE THREAD

**Issue by thiagofigueiro** [papertrail/remote_syslog2#139]
Steps to reproduce:

1. Add a file entry with wildcards to your monitoring (e.g. `  - /home/user/app/log/*.log`)
2. Restart remote_syslog
3. Generate some entries (`for i in {1..3}; do echo asdasdasd$i >> /home/user/app/log/asd.log; done`)
4. Follow events in papertrail web UI

Expected results: see asdasdasd1, asdasdasd2 and asdasdasd3 in web UI
Actual result: see asdasdasd2 and asdasdasd3 in web UI

**Comment by troy** [comment]
Here's what's causing this and a workaround: https://github.com/papertrail/remote_syslog2#detecting-new-files
