### ISSUE TITLE
Does not start in the background

### ISSUE THREAD

**Issue by stuartford** [papertrail/remote_syslog2#147]
Starts fine with -D and logs events to target successfully, but if I try to start it from /etc/init.d or even just without -D it just quits without doing anything. Tried turning on debugging log but the log file (although created) is empty.

Ubuntu 14.0.4 LTS.

**Comment by troy** [comment]
First thought would be a local security policy, like SELinux, but give this a whirl:
http://help.papertrailapp.com/kb/configuration/troubleshooting-remote-syslog-reachability/#test-strace

See what strace says. Something is preventing it from daemonizing. 

This seems like an environment-specific question rather than a bug, so I'd encourage continuing this with Papertrail support (support at papertrailapp.com) instead of in this issue.

**Comment by stuartford** [comment]
I'll give them a whirl, thank you. If they provide me with something that fixes it I'll post back here.

**Comment by johlym** [comment]
It looks like this was the result of a bad pid file that needed expunging.

**Comment by mnapoli** [comment]
I'm facing the same issue (Ubuntu 16.04), with `-D` it runs fine but not in background. What does this means and how can I fix it:

> It looks like this was the result of a bad pid file that needed expunging.

Thanks a bunch! (I've set up remote_syslog successfully many times on many other servers, first time it doesn't work for me)

**Comment by johlym** [comment]
Excellent, @mnapoli! Glad to hear it. On occasion, this happens to me with other apps, too; seemingly more so on 16.04 over previous versions.

**Comment by mnapoli** [comment]
@johlym I was asking what the sentence meant because I didn't understand what I was supposed to do to fix the problem ;) (I can see now that my wording wasn't very clear). But now it works, I don't really know why so…

**Comment by johlym** [comment]
Oof, my bad @mnapoli. I definitely misread that.

If the pid file is corrupt or doesn't belong to a particular instance of remote_syslog2, the process won't be able to get rid of it on exit which leads it to not being able to start up again. Clearing the pid file is all that's typically required to clear this block.

**Comment by mnapoli** [comment]
Ohh OK that's clearer now thanks!
