### ISSUE TITLE
EB docs

### ISSUE THREAD

**Issue by grobmeier** [papertrail/remote_syslog2#150]
Hi,

is this line correct?
https://github.com/papertrail/remote_syslog2/blob/master/examples/remote_syslog.ebextensions.config#L5

It says I need to configure an app name, but there is no variable to replace.

**Comment by johlym** [comment]
Good catch. The app name is set [here](https://github.com/papertrail/remote_syslog2/blob/master/examples/remote_syslog.ebextensions.config#L34) now. Your `App Name` is not your `AWSEBEnvironmentName`.
