### ISSUE TITLE
FreeBSD: ELF binary type "0" not known

### ISSUE THREAD

**Issue by johlym** [papertrail/remote_syslog2#156]
From Papertrail Support email: 

I have followed your instructions below 
http://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-text-log-files-in-unix/ 

When I start "remote_syslog" I receive the following error message. 

ELF binary type "0" not known. 
/usr/local/bin/remote_syslog: 1: Syntax error: end of file unexpected 
(expecting ")") 
/usr/local/bin/remote_syslog: 1: Syntax error: Error in command substitution 
/usr/local/bin/remote_syslog: 1: Syntax error: Error in command substitution 

Here is the OS I am running 
FreeBSD LIP 10.2-RELEASE-p16 FreeBSD 10.2-RELEASE-p16 #0: Wed May 4 
07:38:23 UTC 2016 
root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64 
and I have downloaded the 
remote_syslog_linux_amd64.tar.gz version

**Comment by johlym** [comment]
Need to add `freebsd` and or `openbsd` to https://github.com/papertrail/remote_syslog2/blob/master/Makefile#L11-L12

**Comment by markdascher** [comment]
Fixed by #240
