### ISSUE TITLE
How TLS option work ?

### ISSUE THREAD

**Issue by piellick** [papertrail/remote_syslog2#158]
Hy everyone,
i try to using tls option with graylog, there is option for : 

- login / password auth ?
- certificate auth ?

regards

**Comment by troy** [comment]
The `--tls` option (more in [README](https://github.com/papertrail/remote_syslog2)) uses certificate auth and validates the cert provided by the server against a [large set of root CAs](https://github.com/papertrail/remote_syslog2/blob/master/papertrail/root_ca.go), which is the same set used by common browsers.
