### ISSUE TITLE
missing --version flag

### ISSUE THREAD

**Issue by bartdag** [papertrail/remote_syslog2#161]
Unless I missed something, it is not possible to determine the binary version on the command line, e.g., by running `remote_syslog --version`. 

This would be very helpful when automating the installation of remote_syslog2 with configuration management software such as ansible.

**Comment by johlym** [comment]
Very good point, @bartdag. We had it in the past but it came out before I was ever around so I don't really know why. I'll look at getting it back in.

**Comment by snorecone** [comment]
Fixed in #179
