### ISSUE TITLE
Static build

### ISSUE THREAD

**Issue by mterron** [papertrail/remote_syslog2#162]
Could you please make available a statically linked version of remote_syslog2. It'll be very useful in non glibc environments.

**Comment by johlym** [comment]
Hi @mterron Thanks for the recommendation. What environment(s) are you running remote_syslog2 where glibc isn't a thing?

**Comment by mterron** [comment]
Alpine based vms

**Comment by johlym** [comment]
Ahh ok. That makes sense. @mterron which version of remote_syslog2 are you trying to use?

**Comment by mterron** [comment]
Latest I guess. I haven't been able to try it due to the lack of glibc
On 30 Jun 2016 12:27 pm, "Johnathan Lyman" <notifications@github.com> wrote:

Ahh ok. That makes sense. @mterron <https://github.com/mterron> which
version of remote_syslog2 are you trying to use?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/papertrail/remote_syslog2/issues/162#issuecomment-229528150>,
or mute the thread
<https://github.com/notifications/unsubscribe/AEOr24baTWGjYTzLVCtOpzU7gxdp3Exdks5qQw1tgaJpZM4JBkOf>
.

**Comment by johlym** [comment]
No worries. This should be fixed with the next release. Though the target in #160 was supporting darwin and arm compilation, doing so made me change how I compile the binaries slightly to statically compile the golang code for linux:

```
file ./remote_syslog
remote_syslog: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

The next build should be out sometime in the next week if I play my cards right.
