### ISSUE TITLE
Include RPM spec in github

### ISSUE THREAD

**Issue by jasondcamp** [papertrail/remote_syslog2#164]
Hello,
  Unless I'm missing it, I can't seem to find the rpm spec that you use to build your rpm packages. Is it possible to include that in the github repo? I know I can create one, but I'd prefer to use the same specs that you guys are building the official packages with if possible.  Might as well include any deb packaging files too.

Thanks!
Jason

**Comment by johlym** [comment]
Hi @jasondcamp. We don't have explicit spec files. We call [fpm](https://github.com/jordansissel/fpm) in the [Makefile](https://github.com/papertrail/remote_syslog2/blob/master/Makefile#L107-L139) and feed it bits from [`packaging/Makefile.packaging`](https://github.com/papertrail/remote_syslog2/blob/master/packaging/Makefile.packaging). 

So you're not missing anything.
