### ISSUE TITLE
Facility from ConfigFile seems to be missing

### ISSUE THREAD

**Issue by Jaciones** [papertrail/remote_syslog2#165]
I am trying to set the facility from a config file(log_files.yml) and it seems like it's ignored. When looking at the code, it seems like the ConfigFile (https://github.com/papertrail/remote_syslog2/blob/3284094ffe60217df568598d217f094a1b472664/config_manager.go) doesn't even contain the facility.

Is the only way to set the facility is as a command line parameter on the init.d script? That seems like it should be something settable via config.

**Comment by johlym** [comment]
Hi @Jaciones. With how remote_syslog2 works and the purpose it serves (piping the contents of log files to Papertrail), setting the facility doesn't really add any value so far as I can tell. Each log file is considered a separate program and the host it runs is the sender, but that's it.

It's entirely possible I'm missing something you're seeing or coming up with so if that's the case, let me know. :)
