### ISSUE TITLE
TLS error "unknown authority"

### ISSUE THREAD

**Issue by dereklucas** [papertrail/remote_syslog2#166]
I'm having an issue where remote_syslog is working great without TLS, but if I run `remote_syslog -D -c log_files.yml --tls` it says:

```
2016-07-18 15:13:55 INFO  remote_syslog.go:114 Connecting to logs4.papertrailapp.com:22795 over tls
2016-07-18 15:13:55 CRITICAL  remote_syslog.go:118 Cannot connect to server: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "COMODO RSA Certification Authority")
```

Is there anything I can check to see why this would be happening?

**Comment by johlym** [comment]
Hi @dereklucas interesting. We saw this a with those operating older remote_syslog2 versions that used the older Golang TLS library. This older library didn't support SHA2. I'm definitely seeing failing SSL handshakes on our end so here's a few things to check:

- Make sure you're updated to at least 0.17, preferably 0.18b1. We swapped out a couple libraries to bump perf and stability. I expect to take the beta label off 0.18 in the next week or two. Nothing major has cropped up (or rather nothing showed up that was the cause of the changes in 0.18).
- Update your system's stored [root CA certs for Comodo](https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/620/0/which-is-root-which-is-intermediate).

If neither of those solve your problem, let me know what OS and version you're running.

**Comment by dereklucas** [comment]
Just installed it today based on this: https://gist.github.com/stanlemon/40dfb397e37f85324e25 so it looks like my blind copy and paste had me install 0.13, not the latest. Whoops! I bet that's the issue. I'll let you know if it's not resolved.

**Comment by dereklucas** [comment]
Updating fixed it. 🎉 Thanks!

**Comment by johlym** [comment]
@dereklucas heck yeah! 💃
