### ISSUE TITLE
rename remote_syslog_darwin_amd64

### ISSUE THREAD

**Issue by sethherr** [papertrail/remote_syslog2#186]
Seems unnecessarily complex. I didn't know which package was for mac and had to ask @snorecone

This just means macOS, right? Are there other things darwin_amd64 would be on?

**Comment by johlym** [comment]
@sethherr `darwin` is the name of the OS X unix-y, freebsd-y kernel. If you run `uname -a` on OS X (or macOS, whatever) you'll get:

```
→ uname -a
Darwin YOUR_HOSTNAME 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

One could in theory build for `darwin_x86` though I don't believe it's supported much, anymore, if at all.

**Comment by sethherr** [comment]
Apparently this is a convention in more than just the go world, docker does it too -

<img width="784" alt="screen shot 2016-11-01 at 3 45 11 pm" src="https://cloud.githubusercontent.com/assets/1235441/19910521/ae6d8676-a04a-11e6-8541-616dd4500a36.png">
