### ISSUE TITLE
remote_syslog on Alpine works only with --poll argument

### ISSUE THREAD

**Issue by prometherion** [papertrail/remote_syslog2#195]
I noticed strange behaviour using remote_syslog on Alpine Linux distributions: the only way to tail files correctly is using the argument --poll on tailing log files. I hope it could be useful to others.

**Comment by troy** [comment]
That's probably a byproduct of its decision to be as small as possible; [here's more](https://alpinelinux.org/about/). I've never heard of "musl libc" but its notify functionality probably works differently or was entirely removed. If you investigate this more and find the cause, feel free to reopen this.
