### ISSUE TITLE
remote_syslog memory usage increasing consistently

### ISSUE THREAD

**Issue by shanab** [papertrail/remote_syslog2#198]
I just upgraded from v0.18 to v0.19, and I noticed that the memory usage of remote_syslog is increasing consistently with time.

The below graph shows it:
<img width="989" alt="screen shot 2017-02-08 at 10 39 02" src="https://cloud.githubusercontent.com/assets/1216585/22731717/e35240b8-edeb-11e6-8065-8f288e13587e.png">
The yellow line represents an instance with 0.5GB memory, and the blue line represents an instance with 4G memory. Eventually the instance with 0.5GB crashes because of this.

Also here's a copy of of the output of `top` on the yellow-lined instance, sorted by memory:
```
top - 09:50:49 up 1 day, 44 min,  1 user,  load average: 0.00, 0.00, 0.00
Tasks:  75 total,   1 running,  74 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.0%us,  0.0%sy,  0.0%ni,100.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:    503244k total,   421836k used,    81408k free,    81996k buffers
Swap:        0k total,        0k used,        0k free,   155500k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 2645 root      20   0 98.1m  93m 6020 S  0.0 18.9   0:34.31 remote_syslog
```

OS: Linux 4.4.41-35.53.amzn1.x86_64

**Comment by oviliz** [comment]
This is worrying. Is this project still alive?

**Comment by troy** [comment]
Yep, it is. A good indicator of whether a project is still active or not is the commit history: https://github.com/papertrail/remote_syslog2/commits/master

If you see commits and/or merger pull requests in the last 6-12 months (or in this case, 10+ commits as recently as a few months ago), then the project is probably active.

**Comment by fantyz** [comment]
While not stone dead, saying that it is alive while having a severe issue like this being left open and unanswered for an extend period of time might be stretching it a bit?

**Comment by snorecone** [comment]
Hi @fantyz (and @oviliz) are you experiencing this issue? If so, do you have reproduction steps? Aside from the report here from @shanab we have had no other reports of this, so additional reports reproduction steps would be a helpful contribution.

Based on everything we know, this isn't a severe issue at all; it impacts very few users and may not even be present in the current version.

**Comment by oviliz** [comment]
@snorecone The fact is that nobody turned back to @shanab at the time asking for further details.

**Comment by markdascher** [comment]
@shanab We were never able to duplicate this sort of runaway memory usage, but the latest pre-release [v0.20-beta2](https://github.com/papertrail/remote_syslog2/releases/tag/v0.20-beta2) fixes a couple of goroutine leaks that could happen during log file rotation. (And v0.20-beta1 fixed some other file rotation issues that could've left old files open.) It would take quite a few rotated files to eat up that much memory, but perhaps this had something to do with it?

In any event, please let us know if this is still an issue with v0.20-beta2.

**Comment by joshphp** [comment]
I am experiencing the issue with 0.19 as well, 3 separate instances increased until they were using 65% of the system memory. Any steps to see if it was from issues rotating logs?

**Comment by shanab** [comment]
We very recently switched to using v0.20-beta2, and it seems consistent with regards to memory consumption.

@markdascher thanks for the suggestion.
