### ISSUE TITLE
Is v0.20 "ready"?

### ISSUE THREAD

**Issue by krallin** [papertrail/remote_syslog2#203]
Looks like v0.20 has been in beta for a while. Are there any known blocking issues to releasing it? 

Thanks!

**Comment by markdascher** [comment]
Good point. The main reason it’s not a release is that it was a minor fix for a pretty specific problem, and we’re working on a more thorough update to take its place. This has taken a bit longer than expected (obviously), but the past few weeks have resulted in significant progress.

You’re certainly free to use the beta as well, if you’re having any trouble with rotated log files. We haven’t heard any complaints about it yet.

**Comment by krallin** [comment]
Great, thanks @markdascher!

As an aside, the main reason we're looking at v0.20 is because the earlier version never releases inotify instances (or eventfd for that matter) when a log file is deleted, so if you're monitoring a wildcard and you have logfiles coming in and being deleted later, you'll eventually end up wasting a ton of inotify resources, and run into `ENOSPC` for no good reason at all.
