### ISSUE TITLE
YUM repository?

### ISSUE THREAD

**Issue by dvershinin** [papertrail/remote_syslog2#215]
Can we have a YUM repository setup to facilitate easy upgrades.

The latest release contains

>  "an important bugfix release. Users of v0.19 that experience high memory usage or a cessation of sending logs should upgrade".

But I wouldn't even be aware of it should I have not checked on the releases here.

Should be as easy as ```yum upgrade``` instead.

**Comment by GabrielBianconi** [comment]
+1

**Comment by deoren** [comment]
+1 for yum repo
+1 for apt repo

Even with those wishlist items, many thanks for making this tool available for everyone to use.

**Comment by dfuentes77** [comment]
I keep coming back in hopes that there is a yum repo finally :(

**Comment by dvershinin** [comment]
For anyone struggling on CentOS / RedHat 7 (myself included), I've setup an automated build to a repository of my own

### Setup YUM repository for CentOS 7

    rpm -ivh https://extras.getpagespeed.com/redhat/7/noarch/RPMS/getpagespeed-extras-7-0.el7.gps.noarch.rpm
    yum install remote_syslog2

### To update to a new version of remote_syslog2 

Just send a pull request with the new version number [here](https://github.com/GetPageSpeed/remote-syslog2-rpm/blob/master/remote_syslog2.spec#L48). Merging will trigger the automated build and update the repository with the new RPM.

[About](https://www.getpagespeed.com/redhat) the repository.

**Comment by ollycross** [comment]
@dvershinin is this Yum repository now paywalled?

**Comment by dvershinin** [comment]
@ollycross yep

**Comment by ollycross** [comment]
@dvershinin  Alrighty
