### ISSUE TITLE
arm64 and windows builds and....

### ISSUE THREAD

**Issue by necrose99** [papertrail/remote_syslog2#218]
Dear mark on arm64 server , esp with zip for 32 bit legacy arm7hf or arm7 apps ... 
but thanks for the few tips by email hear a few of my'n own. 

https://www.dropbox.com/s/6hpk14dirlxht4l/remote_syslog2-0.20.tar.xz?dl=0  

compiled with [**gox**](https://github.com/mitchellh/gox) ,  the go build begets a native arm64.. 

gox will do windows linux etc etc.. oh and Bsd as well most of the time... 

linux_armhf.tar.gz  i could use if runing on RPI3-64bit as my gentoo image 
https://github.com/sakaki-/gentoo-on-rpi3-64bit  dose include some legacy 32bit support. 

2018-08-15 20:07:14 CRITICAL  remote_syslog.go:240 Failed to start server: No destination hostname specified
scw-0321f9 /usr/src/remote_syslog2-0.20 # gox
Number of parallel builds: 7

-->      darwin/386: _/usr/src/remote_syslog2-0.20
-->     linux/amd64: _/usr/src/remote_syslog2-0.20
-->   freebsd/amd64: _/usr/src/remote_syslog2-0.20
-->    darwin/amd64: _/usr/src/remote_syslog2-0.20
-->      netbsd/arm: _/usr/src/remote_syslog2-0.20
-->       linux/arm: _/usr/src/remote_syslog2-0.20
-->     freebsd/386: _/usr/src/remote_syslog2-0.20
-->       linux/386: _/usr/src/remote_syslog2-0.20
-->   windows/amd64: _/usr/src/remote_syslog2-0.20
-->     openbsd/386: _/usr/src/remote_syslog2-0.20
-->   openbsd/amd64: _/usr/src/remote_syslog2-0.20
-->     windows/386: _/usr/src/remote_syslog2-0.20
-->     freebsd/arm: _/usr/src/remote_syslog2-0.20
-->    netbsd/amd64: _/usr/src/remote_syslog2-0.20
-->      netbsd/386: _/usr/src/remote_syslog2-0.20

10 errors occurred:
--> freebsd/386 error: exit status 2
Stderr: # github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon
/root/src/github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon/daemon.go:62:19: undefined: GetExecutablePath

--> darwin/386 error: exit status 2
Stderr: # github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon
/root/src/github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon/daemon.go:62:19: undefined: GetExecutablePath

--> netbsd/arm error: exit status 2
Stderr: # github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon
/root/src/github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon/daemon.go:62:19: undefined: GetExecutablePath

--> darwin/amd64 error: exit status 2
Stderr: # github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon
/root/src/github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon/daemon.go:62:19: undefined: GetExecutablePath

--> freebsd/amd64 error: exit status 2
Stderr: # github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon
/root/src/github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon/daemon.go:62:19: undefined: GetExecutablePath

--> openbsd/386 error: exit status 2
Stderr: # github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon
/root/src/github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon/daemon.go:62:19: undefined: GetExecutablePath

--> freebsd/arm error: exit status 2
Stderr: # github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon
/root/src/github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon/daemon.go:62:19: undefined: GetExecutablePath

--> netbsd/amd64 error: exit status 2
Stderr: # github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon
/root/src/github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon/daemon.go:62:19: undefined: GetExecutablePath

--> openbsd/amd64 error: exit status 2
Stderr: # github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon
/root/src/github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon/daemon.go:62:19: undefined: GetExecutablePath

--> netbsd/386 error: exit status 2
Stderr: # github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon
/root/src/github.com/papertrail/remote_syslog2/vendor/github.com/VividCortex/godaemon/daemon.go:62:19: undefined: GetExecutablePath

**Comment by necrose99** [comment]
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Mike-LTPC>C:\Users\Mike-LTPC\Dropbox\remote_syslog2-0.20_windows_amd64.exe
2018-08-15 20:42:45 CRITICAL  remote_syslog.go:240 Failed to start server: No destination hostname specified

C:\Users\Mike-LTPC> 
well all be...

**Comment by markdascher** [comment]
We've added native builds for a few more operating systems in #221 and #240, which should also fix most of those build errors shown above. I'm going to close this issue for now, but please let us know if there's more to do here.

Thanks!
