### ISSUE TITLE
Vendored version of loggo includes a GPLv3 "COPYING" file

### ISSUE THREAD

**Issue by kdykeman** [papertrail/remote_syslog2#219]
The vendored version of `github.com/howbazaar/loggo` includes a [GPLv3 "COPYING" file](https://github.com/howbazaar/loggo/blob/384be41088235af6d26ba66786fd23c45b2d5311/COPYING). In more recent revisions, the COPYING file has been removed and the license is clearly indicated to be LGPLv3. Can you bump to a newer version to reduce possible confusion?

**Comment by kdykeman** [comment]
bump

**Comment by cce** [comment]
The [LICENSE](https://github.com/papertrail/remote_syslog2/blob/master/vendor/github.com/howbazaar/loggo/LICENSE) declaration in that vendored directory says:

> This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation ... See both COPYING and COPYING.LESSER for the full terms of the GNU Lesser General Public License.

The [COPYING.LESSER](https://github.com/papertrail/remote_syslog2/blob/master/vendor/github.com/howbazaar/loggo/COPYING.LESSER) file in that vendored directory says:
>   This version of the GNU Lesser General Public License incorporates the terms and conditions of version 3 of the GNU General Public License, supplemented by the additional permissions listed below.

I believe these three files (LICENSE, COPYING, and COPYING.LESSER) are being distributed together in keeping with the directions for using the LGPL in https://www.gnu.org/licenses/gpl-howto.en.html
