### ISSUE TITLE
syslog does not pass tests under go 1.11.5 so the build shows failed

### ISSUE THREAD

**Issue by ckelloug2** [papertrail/remote_syslog2#223]
There are two errors related to formatting output errors that keep the syslog subpackage from building and passing tests.  The first is in syslog_test.go, the second is in packet_test.go.  I'm including the patch I used to get it to build and pass tests.

diff --git a/syslog/packet_test.go b/syslog/packet_test.go
index ef3e419..6209846 100644
--- a/syslog/packet_test.go
+++ b/syslog/packet_test.go
@@ -17,7 +17,7 @@ func TestPacketPriority(t *testing.T) {
        for _, test := range tests {
                p := Packet{Severity: test.severity, Facility: test.facility}
                if result := p.Priority(); result != test.priority {
-                       t.Errorf("Bad priority, got %s expected %d", result, test.priority)
+                       t.Errorf("Bad priority, got %d expected %d", result, test.priority)
                }
        }
 }
diff --git a/syslog/syslog_test.go b/syslog/syslog_test.go
index 64db446..d4f4c7c 100644
--- a/syslog/syslog_test.go
+++ b/syslog/syslog_test.go
@@ -12,7 +12,7 @@ import (
 
 const clienthost = "clienthost"
 
-func panicf(s string, i ...interface{}) { panic(fmt.Sprintf(s, i)) }
+func panicf(s string, i ...interface{}) { panic(fmt.Sprintf(s, i...)) }
 
 type testServer struct {
        Addr     string

**Comment by cce** [comment]
Thanks! Fixed in #225.
