### ISSUE TITLE
FreeBSD compatible?

### ISSUE THREAD

**Issue by Padrio** [papertrail/remote_syslog2#233]
Since im not very experienced with compiling software on FreeBSD i rather ask first: Is this software optimized to run on FreeBSD?

**Comment by markdascher** [comment]
It is now! We just added FreeBSD support in #240, currently available in the [v0.21-beta1](https://github.com/papertrail/remote_syslog2/releases/tag/v0.21-beta1) release.

**Comment by ivanovv** [comment]
@markdascher do you plan to release that?

**Comment by markdascher** [comment]
Thanks for the reminder! There haven't been any complaints regarding the beta, so we've just released version 0.21 including the additional builds.
