### ISSUE TITLE
Fall back to writing PID file to directory writable by anyone

### ISSUE THREAD

**Issue by troy** [papertrail/remote_syslog2#24]
Try to write the PID file to the same place it does now (typically `/var/run`).

If creating that PID file fails due to permissions, try to use the same filename in the system tempdir (typically `/tmp`). That directory is writable by anyone.

If it's not practical to do that, we can consider changing universally to `/tmp`, but I'd strongly prefer to maintain backward compatibility in cases where we can write to `/var/run`.

**Comment by featalion** [comment]
Resolved by f0f80cdd
Works only If pid file does not set by command line argument.

**Comment by snorecone** [comment]
Closing since this was previously fixed, and I've confirmed that it's working on the latest version: [v0.19](https://github.com/papertrail/remote_syslog2/releases/tag/v0.19)
