### ISSUE TITLE
remote_syslog exits with "too many open files"

### ISSUE THREAD

**Issue by unwiredlabs** [papertrail/remote_syslog2#4]
On Ubuntu 12.04, the remote_syslog2 wouldn't start with the following .yml file. I started it with -D option and this is what I got towards the end:

files: 
- /var/log/apache2/access.log
- /var/log/apache2/error.log
- /opt/misc/*.log
- /var/log/mysql/error.log
- /var/www/weblogs/*.log
- /var/log/Xorg.x.log
- /var/log/alternatives.log
- /var/log/mail.log
- /var/log/messages
- /var/log/dmesg
- /var/log/wtmp
- /var/log/daemon.log
- /var/log/btmp
- /var/log/secure
- /var/log/auth.log
- /var/log/lastlog
- /var/log/boot.log
- /var/log/faillog
- /var/log/anaconda.log
- /var/log/user.log
- /var/log/dkpg.log
- /var/log/cups
- /var/log/kern.log
  destination:
  host: logs.papertrailapp.com
  port: <port>

remote_syslog error output:

2014-05-14 10:48:40 ERROR  remote_syslog.go:76 Cannot forward /var/log/cups, it may not exist
2014-05-14 10:48:40 INFO  remote_syslog.go:86 Forwarding /var/log/kern.log
2014/05/14 16:18:40 FATAL -- Error creating fsnotify watcher: inotify_init: too many open files

I removed the *.log wildcards and the error isn't there anymore.. but what limit is this? And is there a way for the daemon to notify the admin by email instead of quitting silently?

**Comment by deltamualpha** [comment]
Was there any other action on this other than "increase the number of watchers and instances per process" limits? I got bit by this in production and was very unobvious what was going on because of the lack of error messaging until I started launching `remote_syslog` in the foreground.

**Comment by deltamualpha** [comment]
I should also add that I've pushed `/proc/sys/fs/inotify/max_user_instances` and `/proc/sys/fs/inotify/max_user_watches` out far past the number of log files I'm trying to monitor and am still seeing failures on startup.

**Comment by deltamualpha** [comment]
Built it myself. That's a slick build process for go!

`--poll` definitely handles the failure case *better* (it doesn't crash) but still can't watch an arbitrarily large number of files (not that the ruby client could either?)

**Comment by troy** [comment]
@deltamualpha If you're seeing anything unexpected, the most useful thing for debugging and troubleshooting is an `strace -f -s 500 -p 12345` (where 12345 is remote_syslog2's PID) while it's happening. Try to get at least 10 seconds before it happens (or before you make it happen, like by creating or writing to tons of files) and at least 10 seconds after. That at least gives us a fighting chance at seeing what's happening :)

**Comment by deltamualpha** [comment]
Excellent, I've done so. It's about 5 MB; where should I send it? It's a little big for a gist.

**Comment by troy** [comment]
Please send it to support@papertrailapp.com. Feel free to gzip or zip it if you prefer.

**Comment by deltamualpha** [comment]
Aha, reading over the trace myself reveals the problem is not `fs.inotify.max_user_instances`
`fs.inotify.max_user_watches` but the old standby `ulimit -a`. remote_syslog was failing trying to open the 1024th file; increasing `ulimit -a` as root appears to fix it.

**Comment by troy** [comment]
Good catch, @deltamualpha. You may also be able to set it in `/etc/sysctl.conf`, though the shell still may need a specific `ulimit` or profile/bashrc entry.

**Comment by drnic** [comment]
This issue went away for me when updating to v0.18-beta1. Keeping an eye out for recurrences.
