### ISSUE TITLE
newline being added when using it with Go

### ISSUE THREAD

**Issue by sent-hil** [papertrail/remote_syslog2#42]
When I tail the file I see: `2014-10-08 06:46:44 [gowebserver] INFO     page took: 1.146094ms`

However on papertrail I see a new line being appended after each log: https://www.dropbox.com/s/6v9hlqw17j8ghe9/Screenshot%202014-10-07%2023.48.16.png?dl=0

Any idea what's happening?

**Comment by troy** [comment]
Closing because I'm fairly sure the last comment is what is or was happening. Feel free to update if not.
