### ISSUE TITLE
When reconnecting to a syslog server, always send data that was logged locally during the outage

### ISSUE THREAD

**Issue by leonsodhi** [papertrail/remote_syslog2#50]
I've also noticed a delay when r_s2 reconnects where it takes a while to start sending.

**Comment by snorecone** [comment]
This _should_ be working based on [v0.19](https://github.com/papertrail/remote_syslog2/releases/tag/v0.19), as `remote_syslog2` will only read the next data when it can send to a remote server. When reconnecting, it will pick up where it left off. 

If there's a case that comes up where this doesn't happen, we'd need to reopen with repro steps.
