### ISSUE TITLE
Allow include_pattern functionality in combination with existing exclude_pattern

### ISSUE THREAD

**Issue by geekpete** [papertrail/remote_syslog2#54]
My use case is that lots of disaparate apps need to get to a standardised logging format so that logs look at least similar to be able to grep.

Currently log data might be essentially random text as far as patterns and I need to only include specific patterns and ignore the rest. Due mostly in part to multi line logging and the lack of a standardised prefix to use for filtering.

so include_patterns as well as exclude_patterns would be nice to use in combination.

"Only include these patterns as the first rule, then of those filtered results exclude these other patterns.

The include/exclude order should be configurable to allow one to be the primary filter and the other to be the secondary.

**Comment by geekpete** [comment]
Oops. Hit the wrong button.

**Comment by troy** [comment]
I like the concept, but it seems like issues like this:

> The include/exclude order should be configurable to allow one to be the primary filter and the other to be the secondary.

.. make it more likely to be beyond the scope of what rs2 is a great solution for. That said, I might well be wrong, and if you're up for implementing it, describe some specifics and I'm happy to work with you to arrive at something you like and can implement and that the project could merge.

**Comment by ne0c0de** [comment]
i opened a separate issue about this but my aim is same is this issue.

I wrote an exclude pattern that i want only specific lines from log (error logs)

/^((?!error).)*$/i

but yaml parser ther papertrail is using didn't accept that pattern even on a valid yaml file.

Any suggestions appreciated

**Comment by geekpete** [comment]
Will close for now, I haven't the time to create an import export tool/helper but someone else might.
