### ISSUE TITLE
Use standard architecture abbreviation in package names

### ISSUE THREAD

**Issue by dincho** [papertrail/remote_syslog2#57]
[Package releases](https://github.com/papertrail/remote_syslog2/releases/tag/v0.13) are currently using non-standart architecture abbreviations.

- i386 should be used instead of 386
- x86_64 should be used instead of amd64

This is will be helpful for automated installation e.g. Ansible.

**Comment by leonsodhi** [comment]
@dincho, I've changed 386 to i386 in r_s2's makefile, but no standard seems to exist for 64-bit naming. 

Debian-based distributions use [amd64](https://packages.debian.org/stable/admin/0install#pdownload), whereas those based on RedHat use [x86_64](https://fedoraproject.org/wiki/EPEL#What_packages_and_versions_are_available_in_EPEL.3F). I am inclined to leave things as they are for now, as eventually we'll shift over to [deb and rpm](https://github.com/papertrail/remote_syslog2/releases/tag/v0.14-beta-pkgs) packages which will be named differently depending on the distro.

**Comment by dincho** [comment]
Indeed there is no formal standard and this is very subjective issue.
