### ISSUE TITLE
Allow custom tags for files

### ISSUE THREAD

**Issue by rmoriz** [papertrail/remote_syslog2#66]
When using standard syslog, we are able to set tags for each file. This is quite useful if you have a lot of vhosts and render logs per vhost, e.g.

```
/var/www/app/logs/access_log
/var/www/app/logs/error_log
...
/var/www/blog/logs/access_log
/var/www/blog/logs/error_log
```

remote_syslog2 automatically uses the file name, so we lose the capability to separate those files.

**Comment by rmoriz** [comment]
see PR #51

**Comment by leonsodhi** [comment]
Continued in #51
