### ISSUE TITLE
Not logging changes in debug log file

### ISSUE THREAD

**Issue by theschles** [papertrail/remote_syslog2#67]
Hi there,

I'm experimenting with remote_syslog2 0.13 in both Linux-i386 (MySQL error.log) and Windows amd64 (Apache logs -- running remote_syslog in an Administrator-level cmd prompt).  

I've configured remote_syslog to send the data to my local Graylog2 server as protocol:udp (I've also tried protocol:tcp).

remote_syslog2 clearly indicates it's finding the files I'm specifying in my config file.

There's data clearly being added to the specified log files.

But nothing is showing up in the debug file I'm specifying:
- "D:\remote_syslog]debug.log" on Windows
- "./debug.log" on Linux

Nor is anything being received by my local Graylog2 server.

Help? What am I doing wrong?

**Comment by troy** [comment]
I'm not sure :) It's not supported on Windows. If you end up with an strace log of what is happening on Linux, feel free to send it to support@papertrailapp.com.

You may want to test it against a Papertrail syslog endpoint. Nothing about remote_syslog's syslog implementation is Papertrail-specific, but it would provide a known-good receiver and receiver config to debug against.

**Comment by troy** [comment]
BTW, if it saves you time, here's an example of how to use strace to see what a binary is doing: http://help.papertrailapp.com/kb/configuration/troubleshooting-remote-syslog-reachability ("Examine logger daemon activity")

**Comment by theschles** [comment]
Those reachability tips look awesome.  I'll try them later...
