### ISSUE TITLE
Don't require a PID file location to be specified when running as a daemon

### ISSUE THREAD

**Issue by leonsodhi** [papertrail/remote_syslog2#71]
A default path should exist so the daemon doesn't silently fail.

**Comment by featalion** [comment]
@leonsodhi do you want such behaviour even if pid file specified by user via command line argument? In other case, the feature is already present. See f0f80cd

**Comment by leonsodhi** [comment]
@featalion hmm, leave this one with me for the time being. I have seen this issue in the past myself (it took forever to figure out what was going wrong) and a customer recently reported it, but I can't reproduce it now and the code does look reasonable.

**Comment by snorecone** [comment]
Closing this since I've confirmed that this was fixed previously and is working on the latest version: [v0.19](https://github.com/papertrail/remote_syslog2/releases/tag/v0.19)
