### ISSUE TITLE
new file contents not forwarded when using globbing

### ISSUE THREAD

**Issue by michaelshobbs** [papertrail/remote_syslog2#81]
Given the following config, I never see the contents of the newly created file. Perhaps the way the file is written to is the problem? It's created and written to once and then never again, but shouldn't `remote_syslog2` send all the contents when it sees the file get created? Also, I verified there are actual lines in the file as well.

truncated config:
```
files:
- /tmp/dokku-predeploy-tasks-logs/*.log
...
```

output:
```
2015-07-09 21:18:23 INFO  remote_syslog.go:86 Forwarding /tmp/dokku-predeploy-tasks-logs/predeploy-tasks-2015-07-09-21-17-51.log
```

**Comment by troy** [comment]
@michaelshobbs I'm wondering if you're encountering [Detecting new files](https://github.com/papertrail/remote_syslog2#detecting-new-files). Are all writes to the file done within 10 seconds of when it's created?

**Comment by michaelshobbs** [comment]
More than likely yes.

**Comment by michaelshobbs** [comment]
I'll see about modifying how those files get written to.

**Comment by troy** [comment]
@michaelshobbs sounds good. It is changable in the code (from 10s), but you'd have to compile a new build and ensure that the glob could complete fast enough (which would mostly be an issue for huge globs and/or NFS).
