### ISSUE TITLE
Allow running NOT as root

### ISSUE THREAD

**Issue by cooniur** [papertrail/remote_syslog2#82]
It would be better to allow `remote_syslog` running in other users than root by adding an extra parameter `--user={user}`.

**Comment by troy** [comment]
It can already run as users other than root, with no argument at all. That is, this is already supported :) The user you start it as will need permission to write the PID file, but that's it.

**Comment by ivanovv** [comment]
For anyone who stumbled that issue, while having this error in the terminal
```
CRITICAL  remote_syslog.go:240 Failed to start server: No destination hostname specified
```

Most likely you forgot to change the read permissions on the `/etc/log_files.yml` file. 
Depending
