### ISSUE TITLE
Long log entries are truncated

### ISSUE THREAD

**Issue by sfroehler** [papertrail/remote_syslog2#91]
We have some rather long XML Documents we write into our log files. With [remote_syslog](https://github.com/papertrail/remote_syslog) this was no problem. Since we moved to remote_syslog2 these entries are truncated. It looks like this is done after a fixed number of characters (~932 ?).
Is there some setting I can set to increase the max length? Otherwise we would have to move back to remote_syslog. :(

**Comment by troy** [comment]
Here's the cause and an easy resolution: https://github.com/papertrail/remote_syslog_logger/issues/15#issuecomment-137089599

Once you've read that and are aware of the other considerations, use the `--tls` argument (or if you truly want cleartext, `--tcp`) to switch from UDP to TCP.

**Comment by sfroehler** [comment]
Sorry, my bad. I was sure i was already using tls. Unfortunately I did not put the protocol option destination...
Thanks for the hint! ;)
